### ISSUE TITLE
Bug Whyred Nusantara - App dont work in wifi

### ISSUE THREAD

**Issue by inoasfrancisco** [nathanchance/Android-Tools#24]
Hello how are you? 
So I have a whyred and there is a bank application "Banco Pan" of Brazil. After a clean flash I can no longer access the account via Wi-Fi only via data network. 

I'm with nusantara a11 with whyred the test with my wife's cell phone, Santoni, she's on the Nusantara A10 too, and has the same problem with the same app from the bank. I try to access the account via Wi-Fi and a connection error appears, and I can only access via data as well. 

All of the tests were done after a clean flash. In santoni that  was in miui accesses the application both via Wi-Fi and via data. 

Thanky you 
I'm in group telegram nick (sfinoa) 

[logs-2021-03-30-19-51-16.zip](https://github.com/nathanchance/Android-Tools/files/6238531/logs-2021-03-30-19-51-16.zip)

**Comment by nathanchance** [comment]
The reporting bugs guide is for you to report bugs to your ROM, not to me.
