### ISSUE TITLE
Multi-touch 

### ISSUE THREAD

**Issue by YuMore233** [nathanchance/Android-Tools#25]
Attach log
 Multi-touch is not sensitive when using warp flash charge

It may also appear at other times

If you need more information, please contact me to provide

I'm sorry that my English is not very good, the above are all machine translations

Improper language is not my intention

[log folder](https://drive.google.com/folderview?id=1-2c4jicnqa__izr99o_WJu8d6Z07FdWz)

**Comment by nathanchance** [comment]
Report this directly to your ROM. This repo is purely for information, it is not associated with any ROM.
